### ISSUE TITLE
YouTube Support

### ISSUE THREAD

**Issue by ashbash1987** [ashbash1987/ktanemod-twitchplays#15]
_Copy of request on Steam by **SparkerBoy**:_
> Does this work on YouTube streams? If not, is it possible to make a mod for that?

**Comment by samfundev** [comment]
## API Breakdown

YouTube handles chat by polling for messages.

Information about getting authentication:
https://developers.google.com/youtube/v3/live/registering_an_application

After we have authentication, we can get a list of broadcasts:
https://developers.google.com/youtube/v3/live/docs/liveBroadcasts/list

After finding their broadcast (They should only have one) we use their liveChatId to poll for messages:
https://developers.google.com/youtube/v3/live/docs/liveChatMessages/list

We should wait based on the pollingIntervalMillis returned until we make another poll.

Here's the reference for a chat message:
https://developers.google.com/youtube/v3/live/docs/liveChatMessages#resource

We can send chat messages by inserting them:
https://developers.google.com/youtube/v3/live/docs/liveChatMessages/insert
