### ISSUE TITLE
Simon States handler: "blue", "yellow" switched

### ISSUE THREAD

**Issue by stormvsn** [ashbash1987/ktanemod-twitchplays#19]
In the Simon States handler at https://github.com/ashbash1987/ktanemod-twitchplays/blob/master/Assets/Scripts/ComponentSolvers/Modded/SimonStatesComponentSolver.cs#L46 and following, "blue" and "yellow" are switched; telling the module "press blue" will result in pressing yellow and vice versa. Red, green, and the single-letter abbreviations are all correct.

**Comment by stormvsn** [comment]
@bmn fixed this on his fork with 6a73ef4d865ab89f7e3c11aaae1ae7c6f02fb681 .

**Comment by ashbash1987** [comment]
Will look at this with the massive pull request :)

**Comment by ashbash1987** [comment]
Fixed now in feature-tpapi with change 70a6ed58bde8beca8b91110c310e59cd5bdeb5c2.
