### ISSUE TITLE
Astrology ignored "on <n>" and hit Poor Omen immediately, resulting in a strike

### ISSUE THREAD

**Issue by blha303** [ashbash1987/ktanemod-twitchplays#26]
Analysis: https://ktane.timwi.de/More/Logfile%20Analyzer.html#url=https://hastebin.com/raw/obexolagaf (Astrology 86)

Chat log:
```
Qwerky__Syntax: !7 press bad on 1
 Moderator b3ktane:  VoteNay Module 7 got a strike! +1 strike to Qwerky__Syntax
 Moderator b3ktane:  KAPOW  KAPOW The bomb has exploded, with 2:02:09 remaining!  KAPOW  KAPOW
```

**Comment by ashbash1987** [comment]
Implementation of Astrology TP-response is not within the Twitch Plays code, so you'll need to check in with Spare Wizard (@volnrok) to fix the issue.
