### ISSUE TITLE
Hitbox Support

### ISSUE THREAD

**Issue by ashbash1987** [ashbash1987/ktanemod-twitchplays#4]
_Copy of request on Steam by **Remindo**:_
> I'd hope that this will have support for other streaming platforms later on, like Hitbox or Beam.

**Comment by samfundev** [comment]
## API Breakdown

Hitbox handles chat with a websocket.

Developer information can be found at:
http://developers.hitbox.tv/

First we need authentication:
http://developers.hitbox.tv/#authentication

After authentication we need to get a server to connect to:
http://developers.hitbox.tv/#pre-server-connection

And then get the websocket:
http://developers.hitbox.tv/#websocket-id

Apparently if we don't get a server after 8 seconds we're supposed to ping another.
http://developers.hitbox.tv/#server-connection

We get a message for connection and a ping message every minute.
http://developers.hitbox.tv/#post-server-connection

Login into the users channel:
http://developers.hitbox.tv/#login-command

We also might want to logout:
http://developers.hitbox.tv/#logout-command

After logging in we can now send and receive messages:
http://developers.hitbox.tv/#send-message
