### ISSUE TITLE
Beam Support

### ISSUE THREAD

**Issue by ashbash1987** [ashbash1987/ktanemod-twitchplays#5]
_Copy of request on Steam by **Remindo**:_
> I'd hope that this will have support for other streaming platforms later on, like Hitbox or Beam.

**Comment by samfundev** [comment]
## API Breakdown

Beam handles chat with a websocket.

Developer information can be found at:
https://dev.beam.pro/

Beam has a general OAuth reference:
https://dev.beam.pro/reference/oauth/index.html

Looks like we need a application for Twitch Plays.

First we need to get the channel id of the user's stream:
https://beam.pro/api/v1/channels/(username)?fields=id

Then we need to get the websocket of their channel:
https://dev.beam.pro/reference/chat/index.html#chat__connection and https://dev.beam.pro/rest.html#chats__channelId__get

Then we can authenticate:
https://dev.beam.pro/reference/chat/index.html#chat__methods__auth

Then we can send chat messages:
https://dev.beam.pro/reference/chat/index.html#chat__methods__msg

Here's the reference for a chat message:
https://dev.beam.pro/reference/chat/index.html#chat__events__ChatMessage
